controllers/post.controller.js, models/post.model.js
1. build feat search API
2. fix addPost type default
=> Feat search app

app.js, package.json
1. install cors package & use it to add cors header
=> feat. add cors header

models/post.model.js, models/user.model.js
1. user model 初版
2. 在原post.model新增user和ref關係(原userName, userPhoto暫時先保留，待API post.controller.create修正後移除)
=> feat. add user.model(v1) and modified post.model with add user-ref

controllers/user.controller.js, routes/users.js, service/index.js
- 主要是新增 resetUserPassword ，讓使用者可以修改密碼
- 因尚未有  user 的 data, 在 user controller 先寫了getUsers 和 createUser 去測試，有資料後再修改其中一筆 user password，看是否成功，這兩個 function 之後可以刪掉
- errorHandle / successHandle 也是初階版，之後如果改寫第五周上的架構，應該都要再重新調整
=> add user resetPassword

controllers/post.controller.js, models/post.model.js, routes/posts.js
=> update post create

controllers/post.controller.js, models/post.model.js, routes/posts.js
新增 updatelike api
有修改 post model likes 變成陣列接受 userid
一併修改 getpost likes 回傳會是 陣列長度(該篇文章按讚人數)
=> feat. add updatelike edit post likes to array

app.js, controllers/file.controller.js, models/image.model.js, package-lock.json, package.json, routes/files.js
=> add fileupdate

controllers/user.controller.js, helper/utils.js, routes/users.js
新增檔案
- [+] helper/utils.js 新增處理物件內空字串處理
修改檔案
- [!] controllers/user.controller.js 撰寫更新單一使用者資訊功能
- [!] routes/users.js 新增更新單一使用者資訊 router
=> feat：add update user info

controllers/user.controller.js, routes/users.js
修改檔案
- [!] controllers/user.controller.js 修改 try catch
- [!] routes/users.js 修改錯誤處理還有驗證身份
=> 修改錯誤處理還有驗證身份

controllers/user.controller.js, package-lock.json, routes/users.js
列出使用者所有追蹤名單:
POST
路由: /users/getFollowrs
req需要: 使用者id
{
"_id": ""
}
追蹤功能:
POST
路由: /users/follow
req需要: 使用者id、被追蹤者id
{
"_id": "",
"userId": ""
}
=> add followder

models/post.model.js
1. delete field  of userName and userPhoto for addPost API
=> fix. delete userName and userPhoto

controllers/post.controller.js, exceptions/index.js, routes/posts.js, swagger-output.json
1. 修正post route 加入api權限認證
2. 修正post controller統一錯誤管理
3. 修正post controller的swagger API文件
=> feat. modify post route, post controller with authoration and async error

package.json
=> fix. modify package.json setting NODE_ENV for heroku

controllers/post.controller.js, controllers/user.controller.js, models/comment.model.js, models/post.model.js, routes/posts.js, routes/users.js
1. 調整  user/profile
2. 調整 comments.model
3. 調整 posts/addComment/:id
4. 新增 posts/updateComment/:id && posts/deleteComment/:id
5. 調整 posts/search
=> [upload]addComment& getProfile

controllers/user.controller.js, models/user.model.js
1. 修正user model, follow與 befollowed, 改成引用的方式
2. 修正"取得追蹤者名單"與"追蹤"，使前端可以從回覆直接取得userName 、avatar
=> fix getFollowers

controllers/file.controller.js, controllers/post.controller.js, controllers/user.controller.js
=> edit apperror

controllers/post.controller.js, routes/posts.js, swagger-output.json
=> feat. add get likedPost api

app.js, controllers/user.controller.js, routes/files.js, routes/posts.js, routes/users.js
=> fix router name

controllers/post.controller.js, routes/posts.js, swagger-output.json
1. 修正[post] /posts/comment/{id} response回傳user avatar userName資訊
2. search api提供舊到新排序
3. 同步修改swagger
=> fix. addComment resposne for userDetail and add new order in search api

controllers/post.controller.js
=> fix. align like response message

controllers/post.controller.js, routes/posts.js, swagger-output.json
=> feat. add search single post with given id in search-api
